# Generated by Django 5.0.6 on 2024-06-24 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('piece', models.CharField(max_length=255)),
                ('emplacement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('capteur', models.ForeignKey(db_column='capteur_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.capteur')),
            ],
        ),
    ]
